distributors:
  configuration:
    - displayName: "OOO Алматерра"
      sheetTitle: "основной прайс"
      sheetIndex: 0
      markers:
        - marker: "A1:ООО \"АЛМАТЕРРА\""
        - marker: "A3:штрих-код"
      firstContentRow: 4
      columnSpecification:
        id: B
        barcode: A
        name: C
        description: D
        vendor: E
        year: F
        color: G
        sweetness: H
        capacity: I
        alcohol: J
        klass: K
        price: L
    - displayName: "Баядера"
      sheetTitle: ""
      sheetIndex: 0
      markers:
        - marker: "B3:Номенклатура"
        - marker: "C3:HoReCa"
      firstContentRow: 5
      columnSpecification:
        name: B
        price: C
    - displayName: "Провайн"
      sheetTitle: ""
      sheetIndex: 0
      markers:
        - marker: "A1:Item"
        - marker: "B1:Страна"
        - marker: "C1:Item Product Type"
      firstContentRow: 2
      columnSpecification:
        id: A
        name: I
        description: C
        vendor: H
        country: B
        color: E
        klass: G
        stock: L
        price: J
    - displayName: "Ришбур"
      sheetTitle: "price"
      sheetIndex: 0
      markers:
        - marker: "A1:К О Д"
        - marker: "C1:N A M E"
        - marker: "E1:Р І К"
      firstContentRow: 4
      columnSpecification:
        id: A
        name: C
        description: D
        year: E
        sweetness: G
        capacity: F
        alcohol: H
        price: I
    - displayName: "Вайнмарт"
      sheetTitle: ""
      sheetIndex: 0
      markers:
        - marker: "G2:ТОВ \"ВАЙНМАРТ\""
        - marker: "M7:Сорт винограда"
      firstContentRow: 11
      columnSpecification:
        id: J
        name: L
        description:
        vendor: K
        country: G
        region: H
        year: P
        color: R
        sweetness: Q
        grapeType: M
        capacity: N
        alcohol:
        klass: O
        price: S
    - displayName: "Бюро Вин (крепкая группа)"
      sheetTitle: "TDSheet"
      sheetIndex: 0
      markers:
        - marker: "D2:БЮРО ВИН"
        - marker: "B14:М І Ц Н А   Г Р У П А"
        - marker: "I16:Витримка/Рік"
      firstContentRow: 20
      columnSpecification:
        id: C
        name: D
        vendor: B
        year: I
        capacity: J
        alcohol: H
        klass: G
        stock: O
        price: K
    - displayName: "Бюро Вин"
      sheetTitle: "TDSheet"
      sheetIndex: 0
      markers:
        - marker: "D2:БЮРО ВИН"
        - marker: "H14:Класиф."
        - marker: "K14:Колір"
      firstContentRow: 20
      columnSpecification:
        id: C
        name: D
        vendor: B
        year: J
        color: K
        ranking: I
        capacity: L
        klass: G
        stock: Q
        price: M

### Distributor configuration template ###
#- displayName: "Distributor name"
#  sheetTitle: "Main price"
#  sheetIndex: 0
#  markers:
#    - marker: "A1:text"
#    - marker: "B2:text"
#  firstContentRow: 4
#  columnSpecification:
#    id:
#    barcode:
#    name:
#    description:
#    vendor:
#    country:
#    region:
#    cellar:
#    year:
#    date:
#    color:
#    sweetness:
#    soilType:
#    vintage:
#    ranking:
#    grapeType:
#    capacity:
#    alcohol:
#    klass:
#    stock:
#    price: